-- Q1what is the total revenue generated by male vs female customers
select gender,sum(purchase_amount) as revenue
from
customer_shopping
group by gender
limit 4000; 
-- Q2which customer used discount but still spent more than the average purchase amount
select customer_id,purchase_amount
from customedone
r_shopping
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount)
from customer_shopping);

-- Q3which are the top 5 products with the highest average review rating
WITH cte AS (
    SELECT 
        item_purchased,
        ROUND(AVG(review_rating), 2) AS average_rating
    FROM customer_shopping
    GROUP BY item_purchased
)
SELECT item_purchased,average_rating
FROM cte
order by average_rating desc
limit 5;

-- Q4 compare the average purchase amounts between standard and express shipping
select shipping_type,
		round(avg(purchase_amount),2) as comparison_between_std_exp
from customer_shopping
where shipping_type in('Standard','Express')
group by shipping_type;
select * from customer_shopping;

-- Q5Do subcribred customers spend more?
-- compare average spend and total revenue between sub and non suub
select subscription_status,
		round(avg(purchase_amount),2) as average_spending,
        round(sum(purchase_amount),2) as total_revenue,
        count(customer_id) as total_customers
from customer_shopping
where subscription_status in('Yes','No')
group by subscription_status
order by total_revenue,average_spending desc;

-- Q6 Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
	   round(sum(case when discount_applied='Yes' then 1 else 0 end)/count(*)*100,2) as discount_rate
from customer_shopping
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7Segment customers into new,Returning and loyal based on their total
-- number of previous purchases,and show the count of each segment.
with  customer_type as(
select customer_id,
		previous_purchases,
case
	when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
	end as customer_segment
from customer_shopping
)
select customer_segment,count(*) as 'Number of Customers'
from customer_type
group by customer_segment;


-- Q8What are the top 3 most purchased products within each category
with item_count as(
select category,
		item_purchased,
        count(customer_id) as total_orders,
        row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_shopping
group by category,item_purchased
)
select item_rank,
		category,
        item_purchased,
        total_orders
from item_count
where item_rank<=3;

-- Q9 are customers who are repeat buyers(more than 5 previous_purchases) also likely to subscribe?
select subscription_status,
		count(customer_id) as repeat_buyers
from customer_shopping
where previous_purchases>5
group by subscription_status;

-- Q10What is the revenue contribution of each age group
select
		age_group,
		sum(purchase_amount) as revenue_contribution 
from customer_shopping
group by age_group
order by revenue_contribution desc